[package]
name = "axiom-event-log-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.1"
crc32fast = "1.5.0"
memmap2 = "0.9.10"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
